### ISSUE TITLE
Calling component via gradio python client doesn't work

### ISSUE THREAD

**Issue by pablovela5620** [radames/gradio-rerun-viewer#6]
Loaded as API: http://127.0.0.1:7862/ ✔
/Users/pablovela/0Dev/personal/inference-hf-spaces/.pixi/envs/default/lib/python3.12/site-packages/gradio_client/utils.py:1097: UserWarning: file() is deprecated and will be removed in a future version. Use handle_file() instead.
  warnings.warn(
Traceback (most recent call last):
  File "/Users/pablovela/0Dev/personal/inference-hf-spaces/main.py", line 4, in <module>
    result = client.predict(
             ^^^^^^^^^^^^^^^
  File "/Users/pablovela/0Dev/personal/inference-hf-spaces/.pixi/envs/default/lib/python3.12/site-packages/gradio_client/client.py", line 463, in predict
    ).result()
      ^^^^^^^^
  File "/Users/pablovela/0Dev/personal/inference-hf-spaces/.pixi/envs/default/lib/python3.12/site-packages/gradio_client/client.py", line 1485, in result
    return super().result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pablovela/0Dev/personal/inference-hf-spaces/.pixi/envs/default/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/pablovela/0Dev/personal/inference-hf-spaces/.pixi/envs/default/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/pablovela/0Dev/personal/inference-hf-spaces/.pixi/envs/default/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pablovela/0Dev/personal/inference-hf-spaces/.pixi/envs/default/lib/python3.12/site-packages/gradio_client/client.py", line 1113, in _inner
    predictions = self.process_predictions(*predictions)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pablovela/0Dev/personal/inference-hf-spaces/.pixi/envs/default/lib/python3.12/site-packages/gradio_client/client.py", line 1278, in process_predictions
    predictions = self.download_files(*predictions)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pablovela/0Dev/personal/inference-hf-spaces/.pixi/envs/default/lib/python3.12/site-packages/gradio_client/client.py", line 1291, in download_files
    data_ = utils.traverse(data_, self._download_file, utils.is_file_obj)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pablovela/0Dev/personal/inference-hf-spaces/.pixi/envs/default/lib/python3.12/site-packages/gradio_client/utils.py", line 984, in traverse
    new_obj.append(traverse(item, func, is_root))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pablovela/0Dev/personal/inference-hf-spaces/.pixi/envs/default/lib/python3.12/site-packages/gradio_client/utils.py", line 975, in traverse
    return func(json_obj)
           ^^^^^^^^^^^^^^
  File "/Users/pablovela/0Dev/personal/inference-hf-spaces/.pixi/envs/default/lib/python3.12/site-packages/gradio_client/client.py", line 1369, in _download_file
    response.raise_for_status()
  File "/Users/pablovela/0Dev/personal/inference-hf-spaces/.pixi/envs/default/lib/python3.12/site-packages/httpx/_models.py", line 761, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '403 Forbidden' for url 'https://dbf21fc67a7df64cb4.gradio.live/file=6f7c8fd3-3c02-4b2b-95c3-d31966b2d4ea/138970045808400/16'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403

I'm guessing its because its providing back a URL from the rerun rrd file that isn't accessible?

**Comment by pablovela5620** [comment]
Another example where it fails is the official example https://huggingface.co/spaces/radames/gradio_rerun

```python
from gradio_client import Client, file

client = Client("radames/gradio_rerun")
result = client.predict(
		img=file('https://raw.githubusercontent.com/gradio-app/gradio/main/test/test_files/bus.png'),
		api_name="/streaming_repeated_blur"
)
print(result)
```

the version that provides the rrd without yield/streaming works fine

```
from gradio_client import Client

client = Client("radames/gradio_rerun")
result = client.predict(
		x=5,
		y=5,
		z=5,
		api_name="/create_cube_rrd"
)
print(result)
```
